### ISSUE TITLE
System tdlib

### ISSUE THREAD

**Issue by jugendhacker** [alexander-akhmetov/python-telegram#119]
I'm currently trying to package this lib for the Arch User Repo. And I just noticed that you use your own build of tdlib which is not that nice because it's not possible to verify if it was build from the original source or not. Also it is redundant if multiple applications on the system use tdlib. So I'm trying to find out if I could get this lib to use the tdlib already provided by the system. Is this possible?

**Comment by alexander-akhmetov** [comment]
Hi, sure, you can use any tdlib, you need to pass path to the tdjson library when you initialize the Telegram instance:

```python
td = Telegram(
    ...
    library_path='path/to/libtdjson.so',
    ...
)
```

**Comment by jugendhacker** [comment]
But that does not really help for packaging here, because for a system package the path should be set inside the lib.

**Comment by alexander-akhmetov** [comment]
The main reason behind using the built-in version is that it works out of the box in most cases. 

If you want to create a package for AUR and use the shared library instead of the built-in, changes are required. I'm not sure what would be the best solution here, but we should keep the standard working out-of-the-box behaviour. 
You could create a specific (for your package) patch, and apply it before packaging. It might cause problems if something changes in this part of the code, but only for package maintainers (you will have to update the patch), and existing package versions will work. Another way could be to change the library and use `find_library` from `ctypes`, but it requires more work.

**Comment by jugendhacker** [comment]
Okay I patched the AUR to use `find_libary` for now. You can find the diff [here](https://aur.archlinux.org/cgit/aur.git/diff/?h=python-telegram&id=092e7e6b84d6eb14bae3cd98fcb91eae8ca4e998&id2=a52383dddb261d8e4ed8c20e583033bed3c97fc2)

**Comment by alexander-akhmetov** [comment]
That's great, thank you! By the look of it, should be straightforward to fallback to `find_library` if there is no binary, and as a second step release two versions of the library, for those who wants to use their own or system `tdlib`. I'll keep the issue open for now for the first part of changes.
