### ISSUE TITLE
Windows Support?

### ISSUE THREAD

**Issue by TheQuinbox** [alexander-akhmetov/python-telegram#247]
I'm curious why this library doesn't support Windows out-of-the-box. AFAIK TDLib is cross-platform, and it's certainly doable (I've seen it done by one person with at least enough success to compile, not sure if it's missing features though).

**Comment by alexander-akhmetov** [comment]
Hi! I don't have Windows to build and test new tdlib builds with every new release. But you can build it yourself ([instruction](https://github.com/tdlib/td#building)) and specify the path to the dll file. You will also have to change the `files_directory`, because if it's not specified the library uses a hardcoded value:

```python
td = Telegram(
    library_path='path',  # path to the dll file
    files_directory='another/path'  # directory for the tdlib's files (database, images, etc.)
)
```

I'm not sure what else needs to be fixed, maybe nothing. 

You can also use the [docker image](https://hub.docker.com/r/akhmetov/python-telegram/) or Windows Subsystem for Linux.

**Comment by TheQuinbox** [comment]
I think GitHub actions sounds like a great idea for this. Once I'm back at my development machine I'll test and let you know if I can get it to work.

I really like this lib (my only other option for making Telegram clients is Telethon and I'm using wxPython, so async is not viable).
